
import React, { useState, useEffect } from 'react';
import { User, Sale } from '../types';
import { supabase } from '../supabaseClient';
import { 
  CheckCircle2, 
  XCircle, 
  Clock, 
  DollarSign, 
  Users, 
  Search, 
  Loader2,
  TrendingUp,
  Package,
  Calendar,
  ChevronRight,
  Filter,
  ArrowRight
} from 'lucide-react';

interface SellerSalesPageProps {
  user: User | null;
}

const SellerSalesPage: React.FC<SellerSalesPageProps> = ({ user }) => {
  const [sales, setSales] = useState<Sale[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('all');

  useEffect(() => {
    fetchSales();
  }, [user]);

  const fetchSales = async () => {
    if (!user) return;
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('sales')
        .select('*')
        .eq('sellerId', user.id);

      if (error) throw error;
      if (data) setSales(data);
    } catch (err) {
      console.error("Error fetching sales:", err);
    } finally {
      setLoading(false);
    }
  };

  const handleUpdateStatus = async (saleId: string, newStatus: 'approved' | 'rejected') => {
    try {
      const { error } = await supabase
        .from('sales')
        .update({ status: newStatus })
        .eq('id', saleId);

      if (error) throw error;
      
      setSales(sales.map(s => s.id === saleId ? { ...s, status: newStatus } : s));
      
      if (newStatus === 'approved') {
        // Haptic feedback simulation or just a nice toast/alert
        if ('vibrate' in navigator) navigator.vibrate(50);
      }
    } catch (err) {
      alert("Failed to update status.");
    }
  };

  const filteredSales = sales.filter(sale => {
    const matchesSearch = sale.productName.toLowerCase().includes(searchTerm.toLowerCase()) || 
                          sale.resellerName.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = statusFilter === 'all' || sale.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  const stats = {
    totalRevenue: sales.filter(s => s.status === 'approved').reduce((acc, s) => acc + s.amount, 0),
    pendingRevenue: sales.filter(s => s.status === 'pending').reduce((acc, s) => acc + s.amount, 0),
    totalCommissions: sales.filter(s => s.status === 'approved').reduce((acc, s) => acc + s.commission, 0),
    orderCount: sales.length
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-neutral-950 flex flex-col items-center justify-center">
        <Loader2 className="animate-spin text-emerald-500 mb-4" size={40} />
        <p className="text-neutral-500 font-bold uppercase tracking-widest text-[10px]">Loading Ledger...</p>
      </div>
    );
  }

  return (
    <div className="bg-neutral-950 min-h-screen pb-32">
      {/* Header & Stats Banner */}
      <div className="bg-neutral-900/50 border-b border-white/5 pt-8 pb-12 px-4 md:px-8">
        <div className="max-w-6xl mx-auto">
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-10">
            <div>
              <div className="flex items-center space-x-2 text-emerald-500 text-xs font-bold uppercase tracking-widest mb-2">
                <TrendingUp size={14} />
                <span>Financial Overview</span>
              </div>
              <h1 className="text-4xl font-black tracking-tight text-white">Sales Ledger</h1>
              <p className="text-neutral-400 mt-2 font-medium">Manage transactions generated by your Reseller Army.</p>
            </div>
            <div className="flex items-center space-x-2 bg-neutral-950 p-2 rounded-2xl border border-white/10">
               <div className="px-4 py-2">
                  <p className="text-[10px] text-neutral-500 font-bold uppercase">Total Volume</p>
                  <p className="text-xl font-black text-white">${stats.totalRevenue.toLocaleString()}</p>
               </div>
               <div className="w-px h-8 bg-white/10"></div>
               <div className="px-4 py-2">
                  <p className="text-[10px] text-neutral-500 font-bold uppercase">Commission Paid</p>
                  <p className="text-xl font-black text-blue-400">${stats.totalCommissions.toLocaleString()}</p>
               </div>
            </div>
          </div>

          {/* Quick Stats Grid */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
             {[
               { label: 'Orders', val: stats.orderCount, icon: Package, color: 'text-purple-500', bg: 'bg-purple-500/10' },
               { label: 'Pending', val: `$${stats.pendingRevenue}`, icon: Clock, color: 'text-amber-500', bg: 'bg-amber-500/10' },
               { label: 'Resellers', val: '24 Active', icon: Users, color: 'text-blue-500', bg: 'bg-blue-500/10' },
               { label: 'Growth', val: '+12.4%', icon: TrendingUp, color: 'text-emerald-500', bg: 'bg-emerald-500/10' },
             ].map((s, i) => (
               <div key={i} className="bg-neutral-900 border border-white/5 p-4 rounded-2xl hover:border-white/10 transition-colors">
                  <div className={`w-8 h-8 ${s.bg} ${s.color} rounded-lg flex items-center justify-center mb-3`}>
                    <s.icon size={16} />
                  </div>
                  <p className="text-[10px] text-neutral-500 font-bold uppercase tracking-tighter">{s.label}</p>
                  <p className="text-lg font-bold text-white mt-0.5">{s.val}</p>
               </div>
             ))}
          </div>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-4 md:px-8 -mt-6">
        {/* Filter Controls */}
        <div className="bg-neutral-900/80 backdrop-blur-xl border border-white/10 rounded-3xl p-4 shadow-2xl flex flex-col md:flex-row items-center gap-4 mb-8">
           <div className="relative w-full md:w-auto md:flex-grow">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-neutral-500" size={18} />
              <input 
                type="text" 
                placeholder="Search products or resellers..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full bg-neutral-950 border border-white/10 rounded-2xl py-3 pl-12 pr-4 focus:outline-none focus:border-emerald-500 transition-colors text-sm"
              />
           </div>
           <div className="flex w-full md:w-auto p-1 bg-neutral-950 rounded-2xl border border-white/5 overflow-x-auto">
              {['all', 'pending', 'approved', 'rejected'].map((status) => (
                <button 
                  key={status}
                  onClick={() => setStatusFilter(status)}
                  className={`px-4 py-2 rounded-xl text-[10px] font-black uppercase whitespace-nowrap transition-all ${
                    statusFilter === status 
                      ? 'bg-emerald-900 text-white shadow-lg shadow-emerald-950/20' 
                      : 'text-neutral-500 hover:text-white'
                  }`}
                >
                  {status}
                </button>
              ))}
           </div>
        </div>

        {/* Sales List: Mobile Cards / Desktop Table */}
        <div className="space-y-4 md:space-y-0">
          {/* MOBILE VIEW (CARDS) */}
          <div className="grid grid-cols-1 gap-4 md:hidden">
            {filteredSales.length > 0 ? filteredSales.map((sale) => (
              <div key={sale.id} className={`bg-neutral-900 border ${sale.status === 'approved' ? 'border-emerald-500/20 shadow-[0_0_20px_rgba(16,185,129,0.03)]' : 'border-white/5'} rounded-3xl p-5 relative overflow-hidden`}>
                <div className="flex justify-between items-start mb-4">
                  <div className="flex items-center space-x-3">
                    <div className="w-12 h-12 bg-neutral-950 rounded-2xl flex items-center justify-center border border-white/5">
                      <Package size={20} className="text-neutral-600" />
                    </div>
                    <div>
                      <h3 className="font-bold text-sm text-white">{sale.productName}</h3>
                      <p className="text-[10px] text-neutral-500 uppercase font-bold tracking-tighter">via {sale.resellerName}</p>
                    </div>
                  </div>
                  <div className={`px-2 py-1 rounded-lg text-[9px] font-black uppercase ${
                    sale.status === 'approved' ? 'bg-emerald-500/10 text-emerald-500' :
                    sale.status === 'rejected' ? 'bg-red-500/10 text-red-500' :
                    'bg-amber-500/10 text-amber-500'
                  }`}>
                    {sale.status}
                  </div>
                </div>

                <div className="flex justify-between items-end border-t border-white/5 pt-4">
                  <div className="space-y-1">
                    <p className="text-[10px] text-neutral-500 font-bold uppercase">Sale Total</p>
                    <p className="text-xl font-black text-white">${sale.amount.toFixed(2)}</p>
                  </div>
                  <div className="text-right space-y-1">
                    <p className="text-[10px] text-neutral-500 font-bold uppercase">Your Share</p>
                    <p className="text-xl font-black text-emerald-500">${(sale.amount - sale.commission).toFixed(2)}</p>
                  </div>
                </div>

                {sale.status === 'pending' && (
                  <div className="grid grid-cols-2 gap-2 mt-5">
                    <button 
                      onClick={() => handleUpdateStatus(sale.id, 'approved')}
                      className="py-3 bg-emerald-900 text-white rounded-xl text-xs font-bold flex items-center justify-center space-x-2"
                    >
                      <CheckCircle2 size={14} />
                      <span>Approve</span>
                    </button>
                    <button 
                      onClick={() => handleUpdateStatus(sale.id, 'rejected')}
                      className="py-3 bg-neutral-800 text-red-500 rounded-xl text-xs font-bold flex items-center justify-center space-x-2 border border-white/5"
                    >
                      <XCircle size={14} />
                      <span>Reject</span>
                    </button>
                  </div>
                )}
                
                <div className="flex items-center space-x-2 mt-4 text-[10px] text-neutral-600 font-bold">
                   <Calendar size={12} />
                   <span>{new Date(sale.createdAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</span>
                </div>
              </div>
            )) : <EmptyState />}
          </div>

          {/* DESKTOP VIEW (REFINED TABLE) */}
          <div className="hidden md:block bg-neutral-900 border border-white/5 rounded-[40px] overflow-hidden shadow-2xl">
             <table className="w-full text-left">
               <thead>
                 <tr className="border-b border-white/5 text-[10px] text-neutral-500 uppercase font-black tracking-widest">
                   <th className="px-8 py-6">Transaction / Reseller</th>
                   <th className="px-8 py-6">Gross Amount</th>
                   <th className="px-8 py-6">Reseller Share</th>
                   <th className="px-8 py-6">Your Profit</th>
                   <th className="px-8 py-6 text-center">Status</th>
                   <th className="px-8 py-6 text-right">Actions</th>
                 </tr>
               </thead>
               <tbody className="divide-y divide-white/5">
                 {filteredSales.map((sale) => (
                   <tr key={sale.id} className="group hover:bg-white/[0.02] transition-colors">
                     <td className="px-8 py-6">
                       <div className="flex items-center space-x-4">
                         <div className="w-10 h-10 bg-neutral-950 rounded-xl flex items-center justify-center border border-white/5 font-mono text-[10px] text-neutral-700">
                           #{sale.id.split('-')[1] || sale.id.slice(0, 4)}
                         </div>
                         <div>
                           <p className="font-bold text-white group-hover:text-emerald-400 transition-colors">{sale.productName}</p>
                           <p className="text-[10px] text-neutral-500 font-bold uppercase tracking-tight">Sold by {sale.resellerName}</p>
                         </div>
                       </div>
                     </td>
                     <td className="px-8 py-6 font-bold text-white">${sale.amount.toFixed(2)}</td>
                     <td className="px-8 py-6 font-bold text-neutral-500">-${sale.commission.toFixed(2)}</td>
                     <td className="px-8 py-6 font-black text-emerald-500">${(sale.amount - sale.commission).toFixed(2)}</td>
                     <td className="px-8 py-6 text-center">
                        <div className={`inline-flex items-center px-3 py-1.5 rounded-full text-[10px] font-black uppercase border ${
                          sale.status === 'approved' ? 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20' :
                          sale.status === 'rejected' ? 'bg-red-500/10 text-red-500 border-red-500/20' :
                          'bg-amber-500/10 text-amber-500 border-amber-500/20'
                        }`}>
                          {sale.status}
                        </div>
                     </td>
                     <td className="px-8 py-6 text-right">
                       {sale.status === 'pending' ? (
                         <div className="flex items-center justify-end space-x-2">
                           <button 
                             onClick={() => handleUpdateStatus(sale.id, 'approved')}
                             className="p-2.5 bg-emerald-900/20 text-emerald-500 rounded-xl hover:bg-emerald-900 hover:text-white transition-all border border-emerald-500/10"
                           >
                             <CheckCircle2 size={18} />
                           </button>
                           <button 
                             onClick={() => handleUpdateStatus(sale.id, 'rejected')}
                             className="p-2.5 bg-neutral-800 text-neutral-400 rounded-xl hover:bg-red-500/10 hover:text-red-500 transition-all border border-white/5"
                           >
                             <XCircle size={18} />
                           </button>
                         </div>
                       ) : (
                         <span className="text-xs font-bold text-neutral-700 uppercase tracking-widest">Finalized</span>
                       )}
                     </td>
                   </tr>
                 ))}
               </tbody>
             </table>
             {filteredSales.length === 0 && <EmptyState />}
          </div>
        </div>
      </div>
    </div>
  );
};

const EmptyState = () => (
  <div className="py-24 text-center">
    <div className="w-20 h-20 bg-neutral-900 border border-white/5 rounded-full flex items-center justify-center mx-auto mb-6">
      <DollarSign className="text-neutral-700" size={32} />
    </div>
    <h3 className="text-xl font-bold text-white">No sales found</h3>
    <p className="text-neutral-500 mt-2 max-w-xs mx-auto">Once your resellers start moving products, your earnings will appear here.</p>
    <button className="mt-8 px-8 py-3 bg-emerald-900 text-white rounded-xl font-bold hover:bg-emerald-800 transition-all">
       Browse Best Sellers
    </button>
  </div>
);

export default SellerSalesPage;
